spring.application.name=zosh-pos-system

server.port=${PORT:5000}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:pos_bhumi}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cloudinary
cloudinary.cloud-name=chb75b02
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
cloudinary.upload-folder=${CLOUDINARY_UPLOAD_FOLDER:zosh-pos/products}

# Upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Razorpay
razorpay.key.id=${RAZORPAY_KEY_ID:}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET:}